nelmio_api_doc:
    documentation:
        info:
            title: Test Api For Consume External Api
            description: pawel.kiljan@gmail.com
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns: [ /api/ ]
